repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  - repo: https://github.com/jendrikseipp/vulture
    rev: 258fe6a1974e89a2add9a45519a9e9dd9f46154e  # frozen: v2.16
    hooks:
      - id: vulture
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: '01a675ea018f2fb714478a5ffb83fcea8374bb06'  # frozen: v0.15.21
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
    hooks:
      - id: black
        language_version: python3
